'**/*.{ts,js,mjs,cjs}':
  - pnpm eslint --fix
  - pnpm prettier --write

'**/*.{json,yaml,md}':
  - npm run eslint -- --fix
  - npm run prettier -- --write

'**/*.{json,yaml,md}':
  - npm run prettier -- --write
