services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      sh -c   "npx prisma migrate deploy && npm run start:dev"
    healthcheck:
      interval: 5s
      timeout: 5s
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
